# Generated by Django 5.2.5 on 2025-08-29 02:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_field_name_8e8508_idx')],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('operating', 'Operating'), ('maintenance', 'Maintenance'), ('shutdown', 'Shutdown')], default='operating', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='core.field')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_windows', to='core.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rig_kind', models.CharField(choices=[('jackup', 'Jackup'), ('mmwu', 'MMWU'), ('hwu', 'HWU'), ('other', 'Other')], max_length=20)),
                ('day_rate', models.DecimalField(decimal_places=2, help_text='Daily rate in currency units', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('standby', 'Standby'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_rig_name_2babd3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('well_kind', models.CharField(choices=[('platform_well', 'Platform Well'), ('exploration_open_location', 'Exploration Open Location')], max_length=30)),
                ('type', models.CharField(choices=[('exploration', 'Exploration'), ('development', 'Development')], max_length=20)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude for exploration wells', max_digits=10, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude for exploration wells', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='core.field')),
                ('platform', models.ForeignKey(blank=True, help_text='Platform reference for platform wells; null for exploration open location', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='core.platform')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity', models.CharField(help_text='Entity type (model name)', max_length=255)),
                ('entity_id', models.UUIDField(help_text='ID of the affected entity')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('before', models.JSONField(blank=True, help_text='Entity state before change', null=True)),
                ('after', models.JSONField(blank=True, help_text='Entity state after change', null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'entity_id'], name='core_auditl_entity_d1c59f_idx'), models.Index(fields=['at'], name='core_auditl_at_eb413d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['name'], name='core_platfo_name_c3edf4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together={('field', 'name')},
        ),
        migrations.AddIndex(
            model_name='maintenancewindow',
            index=models.Index(fields=['platform', 'start_date'], name='core_mainte_platfor_42567d_idx'),
        ),
        migrations.AddIndex(
            model_name='well',
            index=models.Index(fields=['name'], name='core_well_name_270b11_idx'),
        ),
    ]
